#!/bin/bash

# Log Capture Script for Habitto App
# This script helps capture and analyze console logs from Xcode

echo "📋 Habitto Console Log Capture Helper"
echo "======================================"
echo ""
echo "This script helps you capture console logs from Xcode."
echo ""
echo "HOW TO USE:"
echo "1. Build and run the app in Xcode"
echo "2. Once the app launches, watch the console for 30 seconds"
echo "3. Copy all console output from the moment you see '🚀 AppDelegate: INIT CALLED'"
echo "4. Paste the logs into a file or share them directly"
echo ""
echo "EXPECTED LOG PATTERNS TO LOOK FOR:"
echo ""
echo "✅ App Initialization:"
echo "   🚀 AppDelegate: INIT CALLED"
echo "   🚀 AppDelegate: didFinishLaunchingWithOptions called"
echo ""
echo "✅ Firebase Configuration:"
echo "   ✅ AppDelegate: Firebase configured"
echo "   OR"
echo "   ✅ AppDelegate: Firebase already configured"
echo ""
echo "✅ Authentication:"
echo "   ✅ SyncEngine: User authenticated - uid: {userId}"
echo ""
echo "✅ Migrations (all 4 should complete):"
echo "   ✅ Guest data already migrated for user: {userId}"
echo "   OR"
echo "   ✅ Guest to auth migration complete!"
echo ""
echo "   🔄 MIGRATION: Completion status migration already completed"
echo "   OR"
echo "   🔄 MIGRATION: Completion status migration completed successfully"
echo ""
echo "   🔄 MIGRATION: Completion to Event migration already completed"
echo "   OR"
echo "   ✅ MIGRATION: Successfully migrated X completion records to events"
echo ""
echo "   🔄 XPDataMigration: Migration already completed, skipping"
echo "   OR"
echo "   ✅ XP_MIGRATION_COMPLETE: All data migrated successfully"
echo ""
echo "✅ Sync Engine (authenticated users only):"
echo "   ✅ SyncEngine: startPeriodicSync() call completed"
echo ""
echo "✅ Event Compaction:"
echo "   ✅ EventCompactor: Scheduling completed"
echo ""
echo "⚠️ ERRORS TO WATCH FOR:"
echo "   ❌ SyncEngine: Failed to authenticate user"
echo "   ⚠️ Guest data migration failed"
echo "   ❌ MIGRATION: Failed to..."
echo "   ❌ SyncEngine: Failed to..."
echo ""
echo "======================================"
echo ""
echo "After capturing logs, you can:"
echo "1. Save them to a file: console_logs.txt"
echo "2. Share them for analysis"
echo "3. Use the log analyzer script to check patterns"
echo ""

